apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: repo
spec:
  workspaces:
    - name: rayjobs
      description: A workspace to mount the job YAML.
  steps:
    - name: run-ededup-job
      image: bitnami/kubectl:latest
      script: |
        #!/bin/sh
        git clone -b tektonbranch --depth 1 https://github.com/shahrokhDaijavad/data-prep-kit.git /workspace/rayjobs/data-prep-kit


        